services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: mock-api/Dockerfile
    env_file:
      - ./.env
    ports:
      - "4000:4000"